import "../styles/globals.css";

import "../../public/css/welpodron.core/_collapse/style.min.css";
import "../../public/css/welpodron.core/_accordion/style.min.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <>
          {/* <Script id="use-theme" strategy="beforeInteractive">
            {`
          if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }
          `}
          </Script> */}
          {children}
          {/* <Script src="/js/welpodron.core/utils/script.min.js" />
          <Script src="/js/welpodron.core/animate/script.min.js" />
          <Script src="/js/welpodron.core/_collapse/script.min.js" />
          <Script src="/init.js" /> */}
        </>
      </body>
    </html>
  );
}
